[profile.default]
src = "src"
out = "out"
libs = ["lib"]
bytecode_hash = "none"
evm_version = "cancun"
solc = "0.8.26"
via_ir = true
ffi = true
fs_permissions = [{ access = "read-write", path = ".forge-snapshots/" }]

[fuzz]
runs = 10000
max_test_rejects = 65536
seed = "0x1"

[invariant]
runs = 500
depth = 100
fail_on_revert = false

[profile.ci.fuzz]
runs = 50000
